### ISSUE TITLE
Feature: User can sign up or log in

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/Tap-In-Closet#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up or log in to their account.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the home page of the application, the user will see a sign in/log in screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![X - 1](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/c1b0be76-9a02-4192-9882-2943a5e98bf4)
![X - 2](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/9fe362f9-c1a5-4603-9b5f-c23502b75e44)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to post new user's username and hashedpassword to the users table.
- [x] Test with HTTPie to get new user's information, from the 'users' table, that includes the username, hashedpassword, and userId.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to allow users to log in.
- [x] Update component to add new users that sign up via the sign up option.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
