### ISSUE TITLE
Feature: User can add items to their closet

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/Tap-In-Closet#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add items to their closet.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their items in their closet and add items to it. In add mode, user can categorize their item as either layer, top, dress, bottom, shoes, or accessories. Additionally a counter next to 'Closet' will keep track of amount of total items.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![X - 3](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/1b52d0ef-793c-4596-af14-9ff7c8a7ce15)
![X - 4](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/bc6ec7a7-770a-4995-99d7-af40ce847924)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to post an item to 'Closet', with their respective category selected by the user.
- [x] Update `server.js` to get back all items of clothing in 'Closet' with items under their appropriate category.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show the app's UI and tabs.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
