### ISSUE TITLE
Feature: User can build outfits with 'Dress me'

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/Tap-In-Closet#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can build an outfit.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In 'Dress me' tab, the user can select categories of clothing items, such as layer, top, dress, bottom, shoes, and accessories, to build an outfit. User can carousel through items with previous or next buttons, or select shuffle, to randomize an outfit. Lastly, the user can save the outfit.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![X - 5](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/4ac1cd40-95c0-45b7-a3e0-5e66b52da0f7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to get all items from the 'Closet'.
- [x] Update `server.js` to post the user's newly curated outfit to the outfits table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component with previous and next arrows to allow users to carousel through selected category images.
- [x] Update a component to display the categories in an aesthetic visual way.
- [x] Update the component to only allow users to save outfits when two or more categories are selected.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
