### ISSUE TITLE
Feature: User can view all their saved outfits

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/Tap-In-Closet#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their saved outfits, edit, and delete outfits.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Under the 'Outfits' tab the user will be able to view their saved outfits. He/she can favorite outfits, and edit or delete existing outfits through the edit mode that will look similar to 'Dress me'.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![X - 6](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/596b8aac-7a26-43fb-8ff5-7ba36e471316)
![X - 7](https://github.com/annaaksenov/Tap-In-Closet/assets/121647003/831481d7-29a0-4fef-b0b4-7d22231b0fe0)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to get back all saved outfits.
- [x] Update `server.js` to post favorited outfits to favorites.
- [x] Update `server.js` to post edited outfits.
- [x] Update `server.js` to delete outfits.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to view the 'Outfits' tab with a counter next to 'Outfits'.
- [x] Create a component for favorited outfits.
- [x] Create a component to edit outfits.
- [x] Update component to display the newly edited outfits.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
